Added Eslint and Prettier configurations
sarthology/ovuli pull request #13
Opened 2020-02-29 22:23 UTC by guptavarun619

Basic configuration for Eslint and Perttier are implemented. **NOTE :** I've moved `App.js` to `/src` directory to keep all the `.js` rendering or providing component in a particular dir rather than root dir. And minor modifications of `' ' -> " "`(single/double quotes) or for `,`(comma) are due to prettier config which can be modified according to decisions made by maintainers.

2020-02-29 22:37 UTC, sarthology requested changes
Please delete this file, We are using yarn.

package-lock

2020-02-29 22:43 UTC, sarthology requested changes
PLEASE, check my comments.

2020-02-29 22:43 UTC, sarthology commented on .prettierrc
> +{}
Please add setting here

2020-02-29 22:43 UTC, sarthology commented on src/App.js
> +import "react-native-gesture-handler";
I knew changing this file will create issues. I suggest moving is back. It's giving errors

<img width="349" alt="Screenshot 2020-03-01 at 4 08 33 AM" src="https://user-images.githubusercontent.com/3650216/75616102-e2efff00-5b72-11ea-9961-dc83ad82c714.png">

2020-03-01 05:28 UTC, guptavarun619 commented
As you directed me to move `App.js` back to root directory it's done and i kept `.prettierrc` blank inorder to not make the configurations opinionated to me, though i've pushed some generic and widely accepted configuration to it.

2020-03-01 07:51 UTC, sarthology commented
It looks good know. Please resolve conflicts.

2020-03-01 09:09 UTC, merged

2020-03-01 09:10 UTC, sarthology commented
Congratulations on your first successful PR. 🎉

![](https://media.giphy.com/media/9g8PH1MbwTy4o/giphy.gif)

2020-03-04 11:37 UTC, muskankhedia commented
@sarthology Please do add the gssoc20 tag and easy, beginner, medium or hard tag before merging a PR as announced many times in the slack channel. Else many students may lose points because of this.

Please keep a note of this and also inform your mentors team for the smooth and successful conduct of the program.