Made YourAvgCycle screen
sarthology/ovuli pull request #55
Opened 2020-03-13 10:03 UTC by Rits1272

2020-03-13 10:05 UTC, Rits1272 commented
Closes #49. Please review @sarthology

2020-03-13 10:12 UTC, sarthology commented
There is a bug in it. 
![image](https://user-images.githubusercontent.com/3650216/76611873-32ee9e80-6541-11ea-9e34-6374138db51c.png)

2020-03-13 10:14 UTC, sarthology requested changes

2020-03-13 10:14 UTC, sarthology commented on src/screens/ProfileScreen/AvgCycleScreen.js
> -        <Picker
We have to use picker only.

2020-03-13 10:52 UTC, Rits1272 commented
Will it suffix @sarthology??

2020-03-13 10:58 UTC, sarthology commented
Use this 
https://github.com/rdhox/react-native-smooth-picker

2020-03-13 11:52 UTC, Rits1272 commented
Please review the changes @sarthology

2020-03-14 09:01 UTC, sarthology commented
Works for now.

2020-03-14 09:01 UTC, merged